<?php

declare(strict_types=1);

$siteId = (int) ($site['id'] ?? 0);
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $siteId > 0 ? 'Настройка сайта' : 'Новый сайт' ?> — Ultima Vox CMS</title><link rel="stylesheet" href="/assets/admin.css"></head>
<body class="admin-shell"><aside class="admin-shell__sidebar"><div class="admin-brand">ULTIMA VOX</div><nav class="admin-nav" aria-label="Основная навигация"><a class="admin-nav__item" href="/admin">Обзор</a><a class="admin-nav__item admin-nav__item--active" href="/admin/sites">Сайты</a><a class="admin-nav__item" href="/admin/structure">Структура</a><a class="admin-nav__item" href="/admin/infosystems">Инфосистемы</a><a class="admin-nav__item" href="/admin/layouts">Макеты</a></nav></aside>
<main class="admin-shell__main"><header class="admin-page-header"><div><p class="admin-eyebrow">Sites</p><h1 class="admin-header__title"><?= text($siteId > 0 ? $site['name'] : 'Новый сайт') ?></h1><?php if ($siteId > 0): ?><p class="admin-page-header__description">Код <code><?= text($site['code']) ?></code> после создания не изменяется.</p><?php endif; ?></div><a class="admin-button admin-button--secondary" href="/admin/sites">К списку</a></header>
<?php if (!empty($error)): ?><div class="admin-notice"><?= text($error) ?></div><?php endif; ?><?php if (!empty($saved)): ?><div class="admin-notice">Изменения сохранены.</div><?php endif; ?>
<section class="admin-panel"><form action="<?= $siteId > 0 ? '/admin/sites/' . $siteId : '/admin/sites' ?>" method="post"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><p><label>Название<br><input name="name" value="<?= text($site['name'] ?? '') ?>" maxlength="255" required></label></p><?php if ($siteId > 0): ?><p><strong>Код:</strong> <code><?= text($site['code']) ?></code></p><label><input type="checkbox" name="is_active" value="1"<?= !empty($site['is_active']) ? ' checked' : '' ?><?= ($site['code'] ?? '') === 'default' ? ' disabled' : '' ?>> Сайт активен</label><?php if (($site['code'] ?? '') === 'default'): ?><input type="hidden" name="is_active" value="1"><?php endif; ?><?php else: ?><p><label>Код<br><input name="code" value="<?= text($site['code'] ?? '') ?>" maxlength="120" pattern="[a-z][a-z0-9_-]*" required></label></p><?php endif; ?><div class="admin-actions"><button class="admin-button admin-button--primary" type="submit">Сохранить</button></div></form></section>
<?php if ($siteId > 0): ?><section class="admin-panel"><h2 class="admin-panel__title">Домены</h2><p class="admin-panel__text">Домен хранится без схемы и порта. Один домен сайта может быть основным.</p><?php if ($domains === []): ?><p class="admin-panel__text">Домены ещё не добавлены. Для default-сайта продолжает работать host из APP_URL.</p><?php else: ?><?php foreach ($domains as $domain): ?><div class="admin-actions"><code><?= text($domain['host']) ?></code><?php if (!empty($domain['is_primary'])): ?><strong>основной</strong><?php else: ?><form action="/admin/sites/<?= $siteId ?>/domains/<?= (int) $domain['id'] ?>/primary" method="post"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><button class="admin-button admin-button--secondary" type="submit">Сделать основным</button></form><?php endif; ?><form action="/admin/sites/<?= $siteId ?>/domains/<?= (int) $domain['id'] ?>/delete" method="post"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><button class="admin-button admin-button--secondary" type="submit">Удалить</button></form></div><?php endforeach; ?><?php endif; ?><form action="/admin/sites/<?= $siteId ?>/domains" method="post"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><p><label>Новый домен<br><input name="host" placeholder="example.ru" maxlength="253" required></label></p><label><input type="checkbox" name="is_primary" value="1"> Сделать основным</label><div class="admin-actions"><button class="admin-button admin-button--primary" type="submit">Добавить домен</button></div></form></section><?php endif; ?>
</main></body></html>
