<?php

declare(strict_types=1);
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Сайты — Ultima Vox CMS</title><link rel="stylesheet" href="/assets/admin.css"></head>
<body class="admin-shell"><aside class="admin-shell__sidebar"><div class="admin-brand">ULTIMA VOX</div><nav class="admin-nav" aria-label="Основная навигация"><a class="admin-nav__item" href="/admin">Обзор</a><a class="admin-nav__item admin-nav__item--active" href="/admin/sites">Сайты</a><a class="admin-nav__item" href="/admin/structure">Структура</a><a class="admin-nav__item" href="/admin/infosystems">Инфосистемы</a><a class="admin-nav__item" href="/admin/layouts">Макеты</a></nav></aside>
<main class="admin-shell__main"><header class="admin-page-header"><div><p class="admin-eyebrow">Sites</p><h1 class="admin-header__title">Сайты</h1><p class="admin-page-header__description">Текущий контекст: <strong><?= text($admin_site->name) ?></strong>. Домены определяют публичный SiteContext.</p></div><a class="admin-button admin-button--primary" href="/admin/sites/create">Новый сайт</a></header>
<?php if (!empty($saved)): ?><div class="admin-notice">Изменения сохранены.</div><?php endif; ?>
<section class="admin-panel"><?php if ($sites === []): ?><p>Сайты не найдены.</p><?php else: ?><div class="admin-actions"><?php foreach ($sites as $site): ?><article class="admin-panel"><h2 class="admin-panel__title"><?= text($site['name']) ?></h2><p class="admin-panel__text"><code><?= text($site['code']) ?></code> · <?= !empty($site['is_active']) ? 'активен' : 'выключен' ?><?= !empty($site['primary_host']) ? ' · ' . text($site['primary_host']) : '' ?></p><p class="admin-panel__text">Узлов: <?= (int) $site['node_count'] ?> · инфосистем: <?= (int) $site['infosystem_count'] ?> · доменов: <?= (int) $site['domain_count'] ?></p><div class="admin-actions"><a class="admin-button admin-button--secondary" href="/admin/sites/<?= (int) $site['id'] ?>/edit">Настроить</a><?php if (!empty($site['is_active']) && (int) $site['id'] !== $admin_site->id): ?><form action="/admin/sites/select" method="post"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><input type="hidden" name="site_id" value="<?= (int) $site['id'] ?>"><button class="admin-button admin-button--secondary" type="submit">Работать с сайтом</button></form><?php endif; ?></div></article><?php endforeach; ?></div><?php endif; ?></section>
</main></body></html>
