<?php

declare(strict_types=1);
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Разделы сайта — <?= text($infosystem['name']) ?> — Ultima Vox CMS</title><link rel="stylesheet" href="/assets/admin.css"><link rel="stylesheet" href="/assets/infosystems.css"></head>
<body class="admin-shell"><aside class="admin-shell__sidebar"><div class="admin-brand">ULTIMA VOX</div><nav class="admin-nav" aria-label="Основная навигация"><a class="admin-nav__item" href="/admin">Обзор</a><a class="admin-nav__item" href="/admin/structure">Структура</a><a class="admin-nav__item admin-nav__item--active" href="/admin/infosystems">Инфосистемы</a><a class="admin-nav__item" href="/admin/layouts">Макеты</a></nav></aside>
<main class="admin-shell__main"><header class="admin-page-header"><div><p class="admin-eyebrow"><?= text($infosystem['code']) ?></p><h1 class="admin-header__title">Связанные разделы сайта</h1><p class="admin-page-header__description">Выберите узлы структуры, в которых эта инфосистема является основной.</p></div><div class="admin-actions"><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>/edit">Настройки</a><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>">К контенту</a></div></header>
<?php if (!empty($saved)): ?><div class="admin-notice">Привязки сохранены.</div><?php endif; ?><?php if (!empty($error)): ?><div class="admin-notice admin-notice--error"><?= text($error) ?></div><?php endif; ?>
<form class="admin-form" method="post" action="/admin/infosystems/<?= (int) $infosystem['id'] ?>/bindings"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><section class="admin-panel"><h2 class="admin-panel__title">Структура сайта</h2><p class="admin-field__hint">Один раздел может иметь только одну основную привязку модуля <code>infosystem</code>. Переназначение раздела автоматически заменит предыдущую привязку.</p><?php if ($nodes === []): ?><div class="admin-empty">В структуре сайта пока нет разделов.</div><?php else: ?><div class="admin-form__grid"><?php foreach ($nodes as $node): ?><label class="admin-check admin-field--wide"><input type="checkbox" name="node_ids[]" value="<?= (int) $node['id'] ?>"<?= !empty($bound_node_ids[$node['id']]) ? ' checked' : '' ?>><span style="padding-left:<?= (int) $node['depth'] * 18 ?>px"><code><?= text($node['path']) ?></code> — <?= text($node['name']) ?></span></label><?php endforeach; ?></div><?php endif; ?></section><div class="admin-actions"><button class="admin-button admin-button--primary" type="submit">Сохранить привязки</button><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>/edit">Отмена</a></div></form>
</main></body></html>
