<?php

declare(strict_types=1);

$infosystemId = (int) ($infosystem['id'] ?? 0);
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $infosystemId > 0 ? 'Настройки инфосистемы' : 'Новая инфосистема' ?> — Ultima Vox CMS</title><link rel="stylesheet" href="/assets/admin.css"><link rel="stylesheet" href="/assets/infosystems.css"></head>
<body class="admin-shell"><aside class="admin-shell__sidebar"><div class="admin-brand">ULTIMA VOX</div><nav class="admin-nav" aria-label="Основная навигация"><a class="admin-nav__item" href="/admin">Обзор</a><a class="admin-nav__item" href="/admin/structure">Структура</a><a class="admin-nav__item admin-nav__item--active" href="/admin/infosystems">Инфосистемы</a><a class="admin-nav__item" href="/admin/layouts">Макеты</a></nav></aside>
<main class="admin-shell__main"><header class="admin-page-header"><div><p class="admin-eyebrow">Infosystem</p><h1 class="admin-header__title"><?= text($infosystemId > 0 ? $infosystem['name'] : 'Новая инфосистема') ?></h1><?php if ($infosystemId > 0): ?><p class="admin-page-header__description"><code><?= text($infosystem['code']) ?></code></p><?php endif; ?></div><div class="admin-actions"><?php if ($infosystemId > 0): ?><a class="admin-button" href="/admin/infosystems/<?= $infosystemId ?>/bindings">Разделы сайта</a><a class="admin-button" href="/admin/infosystems/<?= $infosystemId ?>">К контенту</a><?php endif; ?><a class="admin-button" href="/admin/infosystems">К списку</a></div></header>
<?php if (!empty($saved)): ?><div class="admin-notice">Настройки сохранены.</div><?php endif; ?><?php if (!empty($error)): ?><div class="admin-notice admin-notice--error"><?= text($error) ?></div><?php endif; ?>
<form class="admin-form" method="post" action="<?= $infosystemId > 0 ? '/admin/infosystems/' . $infosystemId : '/admin/infosystems' ?>" id="infosystem-form"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>">
<section class="admin-panel"><h2 class="admin-panel__title">Основное</h2><div class="admin-form__grid"><label class="admin-field"><span class="admin-field__label">Название</span><input class="admin-input" name="name" maxlength="255" required value="<?= text($infosystem['name'] ?? '') ?>"></label><label class="admin-field"><span class="admin-field__label">Код</span><input class="admin-input" name="code" maxlength="120" pattern="[a-z][a-z0-9_-]*" required value="<?= text($infosystem['code'] ?? '') ?>"<?= $infosystemId > 0 ? ' readonly' : '' ?>><span class="admin-field__hint">Стабильный системный идентификатор. После создания не меняется.</span></label><label class="admin-field admin-field--wide"><span class="admin-field__label">Описание</span><textarea class="admin-textarea admin-textarea--small" name="description"><?= text($infosystem['description'] ?? '') ?></textarea></label><label class="admin-check admin-field--wide"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1"<?= !empty($infosystem['is_active']) ? ' checked' : '' ?>><span>Инфосистема активна</span></label></div></section>
<section class="admin-panel"><div class="admin-panel-heading"><div><h2 class="admin-panel__title">Дополнительные поля</h2><p class="admin-field__hint">Определения хранятся одной JSONB-схемой. Значения элементов — в <code>properties JSONB</code>.</p></div><button class="admin-button" type="button" id="add-field">Добавить поле</button></div><div class="field-schema" id="field-schema"><?php foreach (($infosystem['field_schema'] ?? []) as $index => $field): ?><?php $optionsValue = is_array($field['options'] ?? null) ? implode(', ', $field['options']) : (string) ($field['options'] ?? ''); ?><div class="field-schema__row" data-field-row><span class="field-schema__drag" title="Порядок полей">⋮⋮</span><input class="admin-input" name="fields[<?= $index ?>][name]" placeholder="Название" value="<?= text($field['name'] ?? '') ?>" required data-name="name"><input class="admin-input" name="fields[<?= $index ?>][code]" placeholder="code" pattern="[a-z][a-z0-9_]*" value="<?= text($field['code'] ?? '') ?>" required data-name="code"><select class="admin-select" name="fields[<?= $index ?>][type]" data-name="type"><?php foreach (['text','textarea','number','boolean','select','date'] as $type): ?><option value="<?= $type ?>"<?= ($field['type'] ?? '') === $type ? ' selected' : '' ?>><?= $type ?></option><?php endforeach; ?></select><input class="admin-input" name="fields[<?= $index ?>][options]" placeholder="Опции через запятую" value="<?= text($optionsValue) ?>" data-name="options"><label class="field-schema__check"><input type="hidden" name="fields[<?= $index ?>][required]" value="0" data-name="required-hidden"><input type="checkbox" name="fields[<?= $index ?>][required]" value="1"<?= !empty($field['required']) ? ' checked' : '' ?> data-name="required"> обяз.</label><label class="field-schema__check"><input type="hidden" name="fields[<?= $index ?>][filterable]" value="0" data-name="filterable-hidden"><input type="checkbox" name="fields[<?= $index ?>][filterable]" value="1"<?= !empty($field['filterable']) ? ' checked' : '' ?> data-name="filterable"> фильтр</label><button class="field-schema__remove" type="button" aria-label="Удалить поле" data-remove-field>×</button></div><?php endforeach; ?></div><p class="admin-field__hint">Для типа <code>select</code> укажите опции через запятую. Флаг «фильтр» документирует поля, предназначенные для публичной фильтрации через GIN.</p></section>
<div class="admin-actions"><button class="admin-button admin-button--primary" type="submit">Сохранить</button><a class="admin-button" href="<?= $infosystemId > 0 ? '/admin/infosystems/' . $infosystemId : '/admin/infosystems' ?>">Отмена</a></div></form>
<?php if ($infosystemId > 0): ?><section class="admin-danger-zone"><div><strong>Удаление инфосистемы</strong><p><?= (int) ($infosystem['node_count'] ?? 0) > 0 ? 'Сначала отвяжите её от всех разделов сайта.' : 'Будут удалены все группы и элементы этой инфосистемы.' ?></p></div><form method="post" action="/admin/infosystems/<?= $infosystemId ?>/delete" onsubmit="return confirm('Удалить инфосистему вместе со всем контентом?');"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><button class="admin-button admin-button--danger" type="submit"<?= (int) ($infosystem['node_count'] ?? 0) > 0 ? ' disabled' : '' ?>>Удалить</button></form></section><?php endif; ?>
</main>
<template id="field-template"><div class="field-schema__row" data-field-row><span class="field-schema__drag">⋮⋮</span><input class="admin-input" placeholder="Название" required data-name="name"><input class="admin-input" placeholder="code" pattern="[a-z][a-z0-9_]*" required data-name="code"><select class="admin-select" data-name="type"><option value="text">text</option><option value="textarea">textarea</option><option value="number">number</option><option value="boolean">boolean</option><option value="select">select</option><option value="date">date</option></select><input class="admin-input" placeholder="Опции через запятую" data-name="options"><label class="field-schema__check"><input type="hidden" value="0" data-name="required-hidden"><input type="checkbox" value="1" data-name="required"> обяз.</label><label class="field-schema__check"><input type="hidden" value="0" data-name="filterable-hidden"><input type="checkbox" value="1" data-name="filterable"> фильтр</label><button class="field-schema__remove" type="button" aria-label="Удалить поле" data-remove-field>×</button></div></template>
<script>(()=>{const container=document.getElementById('field-schema');const template=document.getElementById('field-template');const add=document.getElementById('add-field');const rename=()=>{[...container.querySelectorAll('[data-field-row]')].forEach((row,index)=>{row.querySelectorAll('[data-name]').forEach((input)=>{const key=input.dataset.name.replace('-hidden','');input.name=`fields[${index}][${key}]`;});});};add.addEventListener('click',()=>{container.append(template.content.cloneNode(true));rename();});container.addEventListener('click',(event)=>{const button=event.target.closest('[data-remove-field]');if(!button)return;button.closest('[data-field-row]').remove();rename();});rename();})();</script>
</body></html>
