<?php

declare(strict_types=1);

$groupId = (int) ($group['id'] ?? 0);
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $groupId > 0 ? 'Редактирование группы' : 'Новая группа' ?> — Ultima Vox CMS</title><link rel="stylesheet" href="/assets/admin.css"><link rel="stylesheet" href="/assets/infosystems.css"></head>
<body class="admin-shell"><aside class="admin-shell__sidebar"><div class="admin-brand">ULTIMA VOX</div><nav class="admin-nav" aria-label="Основная навигация"><a class="admin-nav__item" href="/admin">Обзор</a><a class="admin-nav__item" href="/admin/structure">Структура</a><a class="admin-nav__item admin-nav__item--active" href="/admin/infosystems">Инфосистемы</a><a class="admin-nav__item" href="/admin/layouts">Макеты</a></nav></aside>
<main class="admin-shell__main"><header class="admin-page-header"><div><p class="admin-eyebrow"><?= text($infosystem['code']) ?></p><h1 class="admin-header__title"><?= text($groupId > 0 ? $group['name'] : 'Новая группа') ?></h1><?php if (($group['path'] ?? '') !== ''): ?><p class="admin-page-header__description"><code><?= text($group['path']) ?></code></p><?php endif; ?></div><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>">К инфосистеме</a></header>
<?php if (!empty($error)): ?><div class="admin-notice admin-notice--error"><?= text($error) ?></div><?php endif; ?>
<form class="admin-form" method="post" action="<?= $groupId > 0 ? '/admin/infosystems/' . (int) $infosystem['id'] . '/groups/' . $groupId : '/admin/infosystems/' . (int) $infosystem['id'] . '/groups' ?>"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><section class="admin-panel"><h2 class="admin-panel__title">Группа</h2><div class="admin-form__grid"><label class="admin-field"><span class="admin-field__label">Название</span><input class="admin-input" name="name" required maxlength="255" value="<?= text($group['name'] ?? '') ?>"></label><label class="admin-field"><span class="admin-field__label">Slug</span><input class="admin-input" name="slug" required maxlength="255" pattern="[a-z0-9][a-z0-9-]*" value="<?= text($group['slug'] ?? '') ?>"></label><label class="admin-field"><span class="admin-field__label">Родитель</span><select class="admin-select" name="parent_id"><option value="">Корень</option><?php foreach ($groups as $candidate): ?><?php if ($groupId === 0 || (int) $candidate['id'] !== $groupId): ?><option value="<?= (int) $candidate['id'] ?>"<?= ($group['parent_id'] ?? null) !== null && (int) $group['parent_id'] === (int) $candidate['id'] ? ' selected' : '' ?>><?= text($candidate['path'] . ' — ' . $candidate['name']) ?></option><?php endif; ?><?php endforeach; ?></select></label><label class="admin-field"><span class="admin-field__label">Сортировка</span><input class="admin-input" type="number" min="0" name="sorting" value="<?= (int) ($group['sorting'] ?? 0) ?>"></label><label class="admin-field admin-field--wide"><span class="admin-field__label">Описание</span><textarea class="admin-textarea admin-textarea--small" name="description"><?= text($group['description'] ?? '') ?></textarea></label><label class="admin-check admin-field--wide"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1"<?= !empty($group['is_active']) ? ' checked' : '' ?>><span>Группа активна</span></label></div></section><div class="admin-actions"><button class="admin-button admin-button--primary" type="submit">Сохранить</button><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>">Отмена</a></div></form>
<?php if ($groupId > 0): ?><section class="admin-danger-zone"><div><strong>Удаление группы</strong><p><?= (int) ($group['child_count'] ?? 0) > 0 || (int) ($group['item_count'] ?? 0) > 0 ? 'Сначала удалите или перенесите дочерние группы и элементы.' : 'Пустую группу можно удалить безопасно.' ?></p></div><form method="post" action="/admin/infosystems/<?= (int) $infosystem['id'] ?>/groups/<?= $groupId ?>/delete" onsubmit="return confirm('Удалить группу?');"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><button class="admin-button admin-button--danger" type="submit"<?= (int) ($group['child_count'] ?? 0) > 0 || (int) ($group['item_count'] ?? 0) > 0 ? ' disabled' : '' ?>>Удалить</button></form></section><?php endif; ?>
</main></body></html>
