<?php

declare(strict_types=1);

$itemId = (int) ($item['id'] ?? 0);
$publishAt = !empty($item['publish_at']) ? (new DateTimeImmutable((string) $item['publish_at']))->format('Y-m-d\TH:i') : '';
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $itemId > 0 ? 'Редактирование элемента' : 'Новый элемент' ?> — Ultima Vox CMS</title><link rel="stylesheet" href="/assets/admin.css"><link rel="stylesheet" href="/assets/infosystems.css"></head>
<body class="admin-shell"><aside class="admin-shell__sidebar"><div class="admin-brand">ULTIMA VOX</div><nav class="admin-nav" aria-label="Основная навигация"><a class="admin-nav__item" href="/admin">Обзор</a><a class="admin-nav__item" href="/admin/structure">Структура</a><a class="admin-nav__item admin-nav__item--active" href="/admin/infosystems">Инфосистемы</a><a class="admin-nav__item" href="/admin/layouts">Макеты</a></nav></aside>
<main class="admin-shell__main"><header class="admin-page-header"><div><p class="admin-eyebrow"><?= text($infosystem['code']) ?></p><h1 class="admin-header__title"><?= text($itemId > 0 ? $item['name'] : 'Новый элемент') ?></h1><?php if (($item['path'] ?? '') !== ''): ?><p class="admin-page-header__description"><code><?= text($item['path']) ?></code></p><?php endif; ?></div><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>">К инфосистеме</a></header>
<?php if (!empty($saved)): ?><div class="admin-notice">Элемент сохранён.</div><?php endif; ?><?php if (!empty($error)): ?><div class="admin-notice admin-notice--error"><?= text($error) ?></div><?php endif; ?>
<form class="admin-form" method="post" action="<?= $itemId > 0 ? '/admin/infosystems/' . (int) $infosystem['id'] . '/items/' . $itemId : '/admin/infosystems/' . (int) $infosystem['id'] . '/items' ?>"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>">
<section class="admin-panel"><h2 class="admin-panel__title">Основное</h2><div class="admin-form__grid"><label class="admin-field admin-field--wide"><span class="admin-field__label">Название</span><input class="admin-input" name="name" required maxlength="255" value="<?= text($item['name'] ?? '') ?>"></label><label class="admin-field"><span class="admin-field__label">Группа</span><select class="admin-select" name="group_id"><option value="">Корень инфосистемы</option><?php foreach ($groups as $group): ?><option value="<?= (int) $group['id'] ?>"<?= ($item['group_id'] ?? null) !== null && (int) $item['group_id'] === (int) $group['id'] ? ' selected' : '' ?>><?= text($group['path'] . ' — ' . $group['name']) ?></option><?php endforeach; ?></select></label><label class="admin-field"><span class="admin-field__label">Slug</span><input class="admin-input" name="slug" required maxlength="255" pattern="[a-z0-9][a-z0-9-]*" value="<?= text($item['slug'] ?? '') ?>"></label><label class="admin-field admin-field--wide"><span class="admin-field__label">Краткое описание</span><textarea class="admin-textarea admin-textarea--small" name="description"><?= text($item['description'] ?? '') ?></textarea></label><label class="admin-field admin-field--wide"><span class="admin-field__label">Контент</span><textarea class="admin-textarea admin-textarea--content" name="content"><?= text($item['content'] ?? '') ?></textarea></label><label class="admin-field admin-field--wide"><span class="admin-field__label">Meta description</span><textarea class="admin-textarea admin-textarea--small" name="meta_description" maxlength="320"><?= text($item['meta_description'] ?? '') ?></textarea></label></div></section>
<?php if ($fields !== []): ?><section class="admin-panel"><h2 class="admin-panel__title">Дополнительные свойства</h2><div class="admin-form__grid"><?php foreach ($fields as $field): ?><?php $code=(string)$field['code']; $value=$item['properties'][$code] ?? null; ?><?php if ($field['type'] === 'textarea'): ?><label class="admin-field admin-field--wide"><span class="admin-field__label"><?= text($field['name']) ?><?= !empty($field['required']) ? ' *' : '' ?></span><textarea class="admin-textarea admin-textarea--small" name="properties[<?= text($code) ?>]"<?= !empty($field['required']) ? ' required' : '' ?>><?= text(is_scalar($value) || $value === null ? $value : '') ?></textarea></label><?php elseif ($field['type'] === 'boolean'): ?><label class="admin-check"><input type="hidden" name="properties[<?= text($code) ?>]" value="0"><input type="checkbox" name="properties[<?= text($code) ?>]" value="1"<?= !empty($value) ? ' checked' : '' ?>><span><?= text($field['name']) ?></span></label><?php elseif ($field['type'] === 'select'): ?><label class="admin-field"><span class="admin-field__label"><?= text($field['name']) ?><?= !empty($field['required']) ? ' *' : '' ?></span><select class="admin-select" name="properties[<?= text($code) ?>]"<?= !empty($field['required']) ? ' required' : '' ?>><option value="">—</option><?php foreach (($field['options'] ?? []) as $option): ?><option value="<?= text($option) ?>"<?= $value === $option ? ' selected' : '' ?>><?= text($option) ?></option><?php endforeach; ?></select></label><?php else: ?><label class="admin-field"><span class="admin-field__label"><?= text($field['name']) ?><?= !empty($field['required']) ? ' *' : '' ?></span><input class="admin-input" name="properties[<?= text($code) ?>]" value="<?= text(is_scalar($value) || $value === null ? $value : '') ?>" type="<?= $field['type'] === 'number' ? 'number' : ($field['type'] === 'date' ? 'date' : 'text') ?>"<?= $field['type'] === 'number' ? ' step="any"' : '' ?><?= !empty($field['required']) ? ' required' : '' ?>></label><?php endif; ?><?php endforeach; ?></div></section><?php endif; ?>
<section class="admin-panel"><h2 class="admin-panel__title">Публикация</h2><div class="admin-form__grid"><label class="admin-field"><span class="admin-field__label">Статус</span><select class="admin-select" name="status"><?php foreach (['draft','published','archived'] as $status): ?><option value="<?= $status ?>"<?= ($item['status'] ?? '') === $status ? ' selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select></label><label class="admin-field"><span class="admin-field__label">Опубликовать не раньше</span><input class="admin-input" type="datetime-local" name="publish_at" value="<?= text($publishAt) ?>"></label><label class="admin-field"><span class="admin-field__label">Сортировка</span><input class="admin-input" type="number" min="0" name="sorting" value="<?= (int) ($item['sorting'] ?? 0) ?>"></label><label class="admin-check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1"<?= !empty($item['is_active']) ? ' checked' : '' ?>><span>Элемент активен</span></label></div></section><div class="admin-actions"><button class="admin-button admin-button--primary" type="submit">Сохранить</button><a class="admin-button" href="/admin/infosystems/<?= (int) $infosystem['id'] ?>">Отмена</a></div></form>
<?php if ($itemId > 0): ?><section class="admin-danger-zone"><div><strong>Удаление элемента</strong><p>Действие необратимо.</p></div><form method="post" action="/admin/infosystems/<?= (int) $infosystem['id'] ?>/items/<?= $itemId ?>/delete" onsubmit="return confirm('Удалить элемент?');"><input type="hidden" name="_csrf" value="<?= text($csrf_token) ?>"><button class="admin-button admin-button--danger" type="submit">Удалить</button></form></section><?php endif; ?>
</main></body></html>
